// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuil9MAlIO9WJU-UwidAjjxw6Fkiez77Q',
    appId: '1:386555893652:web:b6e3ba19247264352da181',
    messagingSenderId: '386555893652',
    projectId: 'generic-card-game-playtester',
    authDomain: 'generic-card-game-playtester.firebaseapp.com',
    storageBucket: 'generic-card-game-playtester.appspot.com',
    measurementId: 'G-3227FN89HG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLUa2oMS0qcDD3q_W1u9OD3ALKB7G2l6o',
    appId: '1:386555893652:android:cf527fdfd8d5bcc92da181',
    messagingSenderId: '386555893652',
    projectId: 'generic-card-game-playtester',
    storageBucket: 'generic-card-game-playtester.appspot.com',
  );
}
